### ISSUE TITLE
better logo that look more modern an will wlook good as fav.ico

### ISSUE THREAD

**Issue by linadesteem** [evo-cloud/hmake#107]
Hi there, i made a better logo for your project. your new logo that you merged 11 days ago will not look good as fav.ico on your web beacuse its dimension is too high

I made a better modern logo, feel free to use it if you like it

![image](https://user-images.githubusercontent.com/35618068/38075902-24e6688e-335e-11e8-9753-e168b63f437e.png)

![image](https://user-images.githubusercontent.com/35618068/38075906-2897656e-335e-11e8-83a2-0d91ddaafc4e.png)

![image](https://user-images.githubusercontent.com/35618068/38075913-2cfab322-335e-11e8-9587-4af03b1bce9c.png)

**Comment by easeway** [comment]
Thanks! If you agree to release your logo under MIT license, please feel
free to make a Pull Request to submit your logo in "logo" folder. An ".svg"
file is required for a logo, other formats are optional, and not
recommended in PR.

**Comment by nilfanif** [comment]
Thanks sir, I agree to release it under MIT license and will make pupl request as soon as possible, may I know what is the requirements size of .svg file?

**Comment by easeway** [comment]
.svg is vector format. It doesn't matter what size you choose. We can always render a png from svg in any size without loosing quality. BTW, what's the original format of your logo? We require a vector format, otherwise we can scale it to arbitrary size. Thanks!

**Comment by linadesteem** [comment]
Thanks sir i will make pull request

**Comment by rayeukkutadesign** [comment]
It is a vector format sir. o can make it in .svg

**Comment by easeway** [comment]
@linadesteem thanks!
