### ISSUE TITLE
How does hmake decide where vendor tree is?

### ISSUE THREAD

**Issue by taoj-action** [evo-cloud/hmake#109]
I am working on a project which import a library in private repo using "git submodule". That library uses aws-sdk-go. I have put all dependencies under the vendor folder. When using hmake, it complains cannot find aws-sdk-go but I noticed hmake looks for vendor tree under the submodule instead of the main project.

If I don't use hmake, I can get "go build" and "go test" working correctly by setting up GOPATH.

Not sure how hmake decide where to look at "vendor tree"? Is there a way to specify the vendor tree?

**Comment by easeway** [comment]
most likely the source volume mapping is missing:

```yaml
settings:
  docker:
    src-volume: /go/src/your-repo
```

_hmake_ is language agnostic. It has no knowledge about go. Please check the following items:

- `GOPATH` settings inside the container
- Is there a `vendor` folder in submodule? It should not be there
- Is there a `HyperMake` file inside submodule? If yes, launch `hmake` outside submodule

Please use [Exec/Debug mode](http://evo-cloud.github.io/hmake/tutor/execmode/) to get into the container, that helps you inspect the actual environment inside the container and may be helpful to find out the root case.
